%%%% Reference solution for 1D Stefan Diffusion with Dirichlet boundary condition
%%%% Calculation of the time needed for complete evaporation of a wet core in 
%%%% a porous (partially wet) particle
%%%% Copyright: Stefan Radl, IPPT 2015, Graz
%function [time_evap, tEvap0] = evaporation_time(properties, particle, xSurface, xEq,r_core) 
function [time_evap, time_simple] = evaporation_time(properties, particle, xSurface, xEq, r_core) 

R_gas        = 8314.4621; %in J/kMol/K
rho_liquid   = properties.rhoLiquid
MG_liq       = properties.MWLiquid
D_eff        = properties.D_eff
pTotal       = properties.pTotal;
Temp         = properties.Temp;

dParticle    = particle.dParticle
rCoreStar    = particle.rCoreStar
liqPhaseFrac = particle.liqPhaseFrac

%Reference quantities
cTotal     = pTotal ./  R_gas ./ Temp 
Rp         = dParticle ./ 2

time_evap = (rho_liquid * liqPhaseFrac )...
            ./(     cTotal*D_eff ...
                   .*log(( 1 - xSurface)./( 1 - xEq))...
                   .*MG_liq...
              )...
            .* (r_core .* r_core .*(3.*Rp - 2 .* r_core ))...
            ./ (6.*Rp);

time_simple = (rho_liquid * liqPhaseFrac )...
            ./(     cTotal*D_eff ...
                   .*( xEq - xSurface)...
                   .*MG_liq...
              )...
            .* (r_core .* r_core .*(3.*Rp - 2 .* r_core ))...
            ./ (6.*Rp);

