% Function to calculate the concentration of the fluid at the reaction front 
% for second stage reaction for a given reaction front position and time
% Formulars according Wen, "Noncatalytic Heterogenous Solid Fluid Reaction Models"
% models p. 43 eqn. 38
% Copyright: Stefan Radl / Thomas Forgber, IPPT, TU Graz

function [concentration_reaction_front] = Wen_concentration_reaction_front (D_ratio,xi_m,N_sh,ThieleMod,C_A0)

    concentration_reaction_front = C_A0 ...
                                ./ ( ...
                                        1 ...
                                        +D_ratio...
                                        .*(1 - xi_m + xi_m./N_sh)...
                                        .*(ThieleMod .* xi_m .* coth(ThieleMod*xi_m)-1)...
                                   );
end
