% Function to calculate the concentration of the solid 
% for second stage reaction for a given reaction front position and time
% Formulars according Wen, "Noncatalytic Heterogenous Solid Fluid Reaction Models"
% models p. 43 eqn. 40
% Copyright: Stefan Radl / Thomas Forgber, IPPT, TU Graz

function [concentration_solid] = Wen_concentration_solid (xi_m_time, ThieleMod,C_S0,xi_wanted)

    concentration_solid = C_S0 ...
                       .* ( ...
                             1 ...
                             - ( ...
                                 (xi_m_time.*sinh(ThieleMod.*xi_wanted)) ...
                               ./(xi_wanted.*sinh(ThieleMod.*xi_m_time))...
                               )...
                          );
    if (concentration_solid < 0)
       concentration_solid = 0; 
    end
end
