% Function to calculate the conversion of solids
% for first/second stage for a given reaction front position and time
% Steage 1: use xi_m >=1, since conversion only depends on thiele modulus and time
% Formulars according Wen, "Noncatalytic Heterogenous Solid Fluid Reaction Models"
% models p. 43 eqn. 40
% Copyright: Stefan Radl, IPPT, TU Graz

function [conversion] = Wen_conversion (ThieleMod, xi_m, N_sh, D_ratio, currDimlessTime)

    if xi_m>=1
        Omega_vc   = Wen_omegaStage1(ThieleMod, N_sh);
        conversion = 3.0 ...
                  ./ (ThieleMod.*ThieleMod) ...
                  .* (ThieleMod .* coth(ThieleMod) - 1) ...
                  .* currDimlessTime ...
                  ./ Omega_vc ;
    else if xi_m<=0.0
        conversion = 1.0;
    else
        Omega_vc   = Wen_omegaStage2(ThieleMod, N_sh, D_ratio);
        conversion = 1.0 ...
                   - xi_m .* xi_m .* xi_m ...
                   + 3 .* xi_m ...
                  ./ (ThieleMod.*ThieleMod) ...
                  .* ( ...
                         ThieleMod .* xi_m ...
                      .* coth(xi_m .* ThieleMod) - 1 ...
                     );

    end

end
