#!/bin/sh
##################################################################################################################
#ParScale verification case 1: Heat Conduction in a Sphere
#BC: convective flux to the enviroment
#Run 1: constant fluid temperature (for verification)

#copyright: IPPT, Graz University of Technology, 2015

cd ${0%/*} || exit 1    # run from this directory

currdir=$PWD
##########################################################

# 1 - Start Preprocessor
cd octave 
octave < preProcessor.m
cd "$currdir"

# 2 - Run
mpirun -np 1 ParScale < in.file_convective 

# 3 - Start Postprocessor
cd octave
octave < analyticalSolution.m
octave < postProcess.m
octave < postPlots.m

cd "$currdir"



