#!/bin/sh

#***************************************
# Compiles PaScal standalone application
#***************************************

#clean and remove all copulings to 
cd $PASCAL_SRC_DIR/COUPLING_LIGGGHTS
chmod 777 Install.sh
./Install.sh 0
#./Install.sh 1
cd $PASCAL_SRC_DIR

make clean-all


#Compile
make thirdParty -j 4
make fedora_fpic -j 4
