#!/bin/sh
#ParScale test case 1: heat conduction in a sphere
#copyright: IPPT, Graz University of Technology
cd ${0%/*} || exit 1    # run from this directory
rm log
rm erroMsg
rm log.pascal
rm *.eps
rm *.dat
rm *.bin
rm -r 0.*
rm -r 1*
rm -r 2*
rm -r 3*
rm -r 4*
rm -r 5*
rm -r 6*
rm -r 7*
rm -r 8*
rm -r 9*

rm log.*
rm octave/*.png
rm codeInfo.*

rm *.aux
rm *.log
rm *.out 
rm *.gz

rm verificationStats/error_stat.dat
rm species.vol_avg
rm heat.vol_avg
rm octave/test.png
rm octave/Property_evolution.png
rm octave/Stefan_diffu_1D_spherical.png
rm heat.temp_avg
