#!/bin/sh
##################################################################################################################
#ParScale verification case 1: Heat Conduction in a Sphere
#BC: convective flux to the enviroment
#Run 1: constant fluid temperature (for verification)
#Run 2: time-variable fluid temperature

#copyright: IPPT, Graz University of Technology, 2014

cd ${0%/*} || exit 1    # run from this directory

currdir=$PWD
##########################################################
# 1 - Run preProcessor
cd octave
    octave < preProcessor.m
cd $currdir

# 2 - Run Parscale to generate verification data
mpirun -np 1 ParScale < in.file_convective 

# 3 - Run postProcessor
cd octave 
    octave < Main_stefan_diffu.m 
cd $currdir
